/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnomalyDetectorRouteImport } from './routes/anomaly-detector'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiLatestAnalysisRouteImport } from './routes/api/latest-analysis'
import { Route as MatchIdRouteImport } from './routes/match.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalyDetectorRoute = AnomalyDetectorRouteImport.update({
  id: '/anomaly-detector',
  path: '/anomaly-detector',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLatestAnalysisRoute = ApiLatestAnalysisRouteImport.update({
  id: '/api/latest-analysis',
  path: '/api/latest-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomaly-detector': typeof AnomalyDetectorRoute
  '/login': typeof LoginRoute
  '/api/latest-analysis': typeof ApiLatestAnalysisRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomaly-detector': typeof AnomalyDetectorRoute
  '/login': typeof LoginRoute
  '/api/latest-analysis': typeof ApiLatestAnalysisRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anomaly-detector': typeof AnomalyDetectorRoute
  '/login': typeof LoginRoute
  '/api/latest-analysis': typeof ApiLatestAnalysisRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/anomaly-detector' | '/login' | '/api/latest-analysis' | '/match/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/anomaly-detector' | '/login' | '/api/latest-analysis' | '/match/$id'
  id:
    | '__root__'
    | '/'
    | '/anomaly-detector'
    | '/login'
    | '/api/latest-analysis'
    | '/match/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnomalyDetectorRoute: typeof AnomalyDetectorRoute
  LoginRoute: typeof LoginRoute
  ApiLatestAnalysisRoute: typeof ApiLatestAnalysisRoute
  MatchIdRoute: typeof MatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomaly-detector': {
      id: '/anomaly-detector'
      path: '/anomaly-detector'
      fullPath: '/anomaly-detector'
      preLoaderRoute: typeof AnomalyDetectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/latest-analysis': {
      id: '/api/latest-analysis'
      path: '/api/latest-analysis'
      fullPath: '/api/latest-analysis'
      preLoaderRoute: typeof ApiLatestAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnomalyDetectorRoute: AnomalyDetectorRoute,
  LoginRoute: LoginRoute,
  ApiLatestAnalysisRoute: ApiLatestAnalysisRoute,
  MatchIdRoute: MatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
